<div class="container">
    <div class="row">
        <h1 class="h1 col-xs-12"><?php echo $this->getPageTitle() ?></h1>

        <form action="/post/<?php echo $this->data->post->id ?>/update" method="post" accept-charset="utf-8">

            <div class="col-sm-10">
                <div class="form-group <?php echo ($this->error['title']) ? 'has-error' : '' ?>">
                    <label for="title" class="control-label">Title</label>
                    <input type="text" name="title" class="form-control"
                           value="<?php echo (isset($this->inputs['title'])) ? $this->inputs['title'] : $this->data->post->title ?>">
                    <?php if ($this->error['title']): ?>
                        <span class="help-block"><?php echo $this->error['title'] ?></span>
                    <?php endif; ?>
                </div>

                <div class="form-group <?php echo ($this->error['content']) ? 'has-error' : '' ?>">
                    <label for="content" class="control-label">Content</label>
                    <textarea name="content" class="form-control"
                              rows="10"><?php echo (isset($this->inputs['content'])) ? $this->inputs['content'] : $this->data->post->content ?></textarea>
                    <?php if ($this->error['content']): ?>
                        <span class="help-block"><?php echo $this->error['content'] ?></span>
                    <?php endif; ?>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group <?php echo ($this->error['category_id']) ? 'has-error' : '' ?>">
                    <label for="title" class="control-label">Categories</label>
                    <?php foreach ($this->data->categories as $cat) : ?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="category_id[]" value="<?php echo $cat->id ?>"
                                    <?php foreach ($this->data->post->category as $item)
                                        echo ($cat->id == $item->id) ? 'checked' : '';
                                    ?>
                                >
                                <?php echo $cat->name ?>
                            </label>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <div class="col-xs-12">
                <a href="/posts" class="btn btn-default">Cancel</a>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>
    </div>
</div>